import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class RazorpayVerifyDto {
  @ApiProperty({
    example: 'pay_Roo9mA11kQqPYa',
    description: 'Razorpay payment ID returned from frontend',
  })
  @IsNotEmpty()
  @IsString()
  razorpay_payment_id: string;

  @ApiProperty({
    example: 'order_RonMRQ2G2fTPgv',
    description: 'Razorpay order ID generated by backend',
  })
  @IsNotEmpty()
  @IsString()
  razorpay_order_id: string;

  @ApiProperty({
    example: '5d889931b10a0c1e6d8f5e9ddf5c6c1e7bd806763...',
    description: 'HMAC-SHA256 signature generated by Razorpay',
  })
  @IsNotEmpty()
  @IsString()
  razorpay_signature: string;
}
